---
title: "GCS Regiones"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project regions

https://data.humdata.org/dataset/colombia-administrative-boundaries-levels-0-3 

```{r cars}
library(leaflet)
library(rgdal)

munis <- readOGR(system.file("dataR/municipios_col/col_admbnda_adm2_unodc_ocha.shp", package = "GanaderiaSostenible"),
  #layer = "cb_2013_us_state_20m", 
  GDAL1_integer64_policy = TRUE)

gcs_reg <- readOGR(system.file("dataR/regiones_gcs/RegionesGCS/scr_project_areas_Adjusted.shp", package = "GanaderiaSostenible"),
  #layer = "cb_2013_us_state_20m", 
  GDAL1_integer64_policy = TRUE)

leaflet(gcs_reg) %>%
  leaflet(munis) %>% 
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    #fillColor = ~colorQuantile("YlOrRd", ALAND)(ALAND),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE))
  
  

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
